# Generated and used by devp/lint-go-default. Can be safely added to .gitignore
#file: noinspection SpellCheckingInspection
run:
  concurrency: 4
  deadline: 30m
linters-settings:
  cyclop:
    max-complexity: 15
  goconst:
    ignore-tests: true
    match-constant: false
  gocritic:
    disabled-checks:
      - commentFormatting
  mnd:
    ignored-numbers:
      - '0644'
      - '0755'
  gosec:
    config:
      G306: "0644"
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 160
  nakedret:
    max-func-lines: 0
  nolintlint:
    require-explanation: true
    require-specific: true
  stylecheck:
    dot-import-whitelist: []
    http-status-code-whitelist: []
    checks: ["all", "-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
  usestdlibvars:
    time-month: true
    time-layout: true
    crypto-hash: true
    default-rpc-path: true
    tls-signature-scheme: true
    constant-kind: true
# https://golangci-lint.run/usage/configuration/#linters-configuration
linters:
  disable-all: true
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - copyloopvar
    - cyclop
    - dogsled
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - err113
    - mnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - linters:
        - staticcheck
      text: 'SA1019:'
    - path-except: pkg\/
      linters:
        - err113
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocyclo
        - err113
        - mnd
        - gosec
        - lll
        - prealloc
  skip-files:
    - ".*\\_gen\\.go$"
    - ".*\\.gen\\.go$"
    - ".*\\_gen\\_test\\.go$"
    - ".*\\.gen\\_test\\.go$"
    - ".*\\.pb\\.go$"
  skip-dirs:
    - mock
    - vendor
    - testdata
    - test_data
output:
  uniq-by-line: false
